touch auto-pairs.vim
touch coc.vim
touch fzf.vim
touch gina.vim
touch git-messenger.vim
touch goyo.vim
touch lightline.vim
touch limelight.vim
touch neoformat.vim
touch neomake.vim
touch rainbow_parentheses.vim
touch vim-commentary.vim
touch vim-dadbod.vim
touch vim-devicons.vim
touch vim-elixir.vim
touch vim-floaterm.vim
touch vim-matchup.vim
touch vim-rooter.vim
touch vim-signify.vim
touch vim-sneak.vim
touch vim-startify.vim
touch vim-surround.vim
touch vim-which-key.vim
touch vista.vim
