return {

  

	"AndrewRadev/tagalong.vim",
	"David-Kunz/markid",
	"L3MON4D3/LuaSnip",
	"RRethy/nvim-treesitter-endwise",
	"ahmedkhalf/project.nvim",
	"alvan/vim-closetag",
	"andymass/vim-matchup",
	"antoinemadec/FixCursorHold.nvim",
	"dstein64/vim-startuptime",
	"elixir-editors/vim-elixir",
	"folke/lsp-colors.nvim",
	"folke/trouble.nvim",
	"hrsh7th/cmp-buffer",
	"hrsh7th/cmp-cmdline",
	"hrsh7th/cmp-nvim-lsp",
	"hrsh7th/cmp-nvim-lsp-document-symbol",
	"hrsh7th/cmp-nvim-lua",
	"hrsh7th/cmp-path",
	"hrsh7th/nvim-cmp",
	"jose-elias-alvarez/null-ls.nvim",
	
	"kassio/neoterm",
	"kdheepak/lazygit.nvim",
	"kyazdani42/nvim-tree.lua",
	"kyazdani42/nvim-web-devicons",
	"kylechui/nvim-surround",
	"lewis6991/gitsigns.nvim",
	"lewis6991/impatient.nvim",
	"lukas-reineke/indent-blankline.nvim",
	"machakann/vim-sandwich",
	"mg979/vim-visual-multi",
	"nat-418/boole.nvim",
	"nathom/filetype.nvim",
	"neovim/nvim-lspconfig",
	"numToStr/Comment.nvim",
	"nvim-lua/plenary.nvim",
	"nvim-lua/popup.nvim",
	"nvim-treesitter/nvim-treesitter",
	"ojroques/nvim-hardline",
	"onsails/lspkind-nvim",
	"pechorin/any-jump.vim",
	"phaazon/hop.nvim",
	"rafamadriz/friendly-snippets",
	"ray-x/guihua.lua",
	"ray-x/lsp_signature.nvim",
	"ray-x/sad.nvim",
	"rmagatti/goto-preview",
	"ruifm/gitlinker.nvim",
	"saadparwaiz1/cmp_luasnip",
	"simrat39/symbols-outline.nvim",
	"tamago324/nlsp-settings.nvim",
	"tjdevries/nlua.nvim",
	"tpope/vim-dispatch",
	"tpope/vim-repeat",
	"vim-test/vim-test",
	"weilbith/nvim-code-action-menu",
	
	"windwp/nvim-autopairs",
	"wsdjeg/vim-fetch",
}

