require("user.options")
require("user.keymaps")
require("user.general")

require("user.plugins")

require("user.lsp")

require("user.autopairs")
require("user.cmp")
require("user.colorscheme")
require("user.comment")
require("user.elixir")
require("user.gitlinker")
require("user.gitsigns")
require("user.hop")
require("user.impatient")
require("user.indent-blankline")
require("user.lsp-signature")
require("user.lualine")
require("user.nvim-tree")
require("user.sad")
require("user.trouble")
require("user.vgit")
require("user.vim-test")
