require("user.options")
require("user.keymaps")
require("user.general")

require("user.plugins")

require("user.treesitter")
require("user.lsp")

require("user.autopairs")
require("user.autotags")
require("user.cmp")
require("user.colorscheme")
require("user.comment")
require("user.elixir")
require("user.html")
require("user.fzf")
require("user.gitlinker")
require("user.gitsigns")
require("user.goto-preview")
require("user.hardline")
require("user.hop")
require("user.impatient")
require("user.indent-blankline")
require("user.nvim-tree")
require("user.project")
require("user.sad")
require("user.symbols-outline")
require("user.trouble")
require("user.vgit")
require("user.vgit")
require("user.vim-test")
require("user.neoterm")
require("user.vim-visual-multi")
